## Read transect or GCP file and report bounding box in lat/lon

#### EPSG::4326

According to http://spatialreference.org/ref/epsg/4326/
```
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.01745329251994328,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]
```

#### EPSG::26919

According to http://www.epsg-registry.org/
```
PROJCRS["NAD83 / UTM zone 19N",
  BASEGEODCRS["NAD83",
    DATUM["North American Datum 1983",
      ELLIPSOID["GRS 1980",6378137,298.257222101,LENGTHUNIT["metre",1.0]]]],
  CONVERSION["UTM zone 19N",
    METHOD["Transverse Mercator",ID["EPSG",9807]],
    PARAMETER["Latitude of natural origin",0,ANGLEUNIT["degree",0.01745329252]],
    PARAMETER["Longitude of natural origin",-69,ANGLEUNIT["degree",0.01745329252]],
    PARAMETER["Scale factor at natural origin",0.9996,SCALEUNIT["unity",1.0]],
    PARAMETER["False easting",500000,LENGTHUNIT["metre",1.0]],
    PARAMETER["False northing",0,LENGTHUNIT["metre",1.0]]],
  CS[cartesian,2],
    AXIS["easting (E)",east,ORDER[1]],
    AXIS["northing (N)",north,ORDER[2]],
    LENGTHUNIT["metre",1.0],
  ID["EPSG",26919]]
  ```

In [1]:
import pandas as pd
import os
from pyproj import Proj, transform

latlonProj = Proj(init='epsg:4326')
utmProj    = Proj(init='epsg:26919')

dirname = r"R:\2015-2017_Sandwich\2017datarelease\GCPs"
fname = r"2017_All_SandwichTNB_in_place_GCPs.txt"
pathname = os.path.join(dirname, fname)
print(pathname)

R:\2015-2017_Sandwich\2017datarelease\GCPs\2017_All_SandwichTNB_in_place_GCPs.txt

In [3]:
df = pd.read_csv(pathname, sep=',',header=None)
df.columns=['id','easting','northing','elev']
df

               id      easting      northing    elev
0   65 FRMN GRATE  376324.5012  4.625223e+06  3.9079
1            BBR1  376478.4387  4.625106e+06  2.5159
2          BBR1_2  376478.4398  4.625106e+06  2.5339
3            BBR5  376468.0722  4.625148e+06  3.8641
4            BBR9  376441.6513  4.625171e+06  4.3488
5     E_BWALK_FAT  376675.7055  4.624825e+06  2.5010
6       E_BWALK_T  376743.1605  4.624875e+06  2.8632
7     E_BDWLK_T_2  376743.1940  4.624875e+06  2.8711
8     FMN GRATE N  376361.8379  4.625143e+06  4.2170
9     FMN GRATE W  376383.5036  4.625054e+06  3.7336
10            JR4  377018.2890  4.624864e+06  0.1911
11  WHITECAP PATH  376363.4749  4.625263e+06  3.7427

In [14]:
lon,lat=transform(utmProj,latlonProj,df['easting'].values,df['northing'].values)

print('westbc: ',lon.min(),'eastbc: ',lon.max())
print('northbc: ',lat.max(),'southbc: ',lat.min())

westbc:  -70.4879640073 eastbc:  -70.479545353
northbc:  41.7695871544 southbc:  41.7656898414

In [19]:
fname2='2017-01-09_SandwichTNB_GCPs.txt'
pathname2 = os.path.join(dirname, fname2)
print(pathname2)
df2 = pd.read_csv(pathname2, sep=',',skiprows=1)
df2

R:\2015-2017_Sandwich\2017datarelease\GCPs\2017-01-09_SandwichTNB_GCPs.txt

        #Label  X/Easting (m)  Y/Northing (m)  Z/Elevation (m)
0           P1    376701.0628    4.624984e+06           5.9625
1           P2    376533.7538    4.625141e+06           5.2526
2           P3    376417.9532    4.625248e+06           1.9856
3           P4    376395.8022    4.625347e+06          -0.0651
4           P5    376553.4078    4.625066e+06           2.7112
5           P6    376670.0570    4.624939e+06           2.6143
6           T1    376763.8347    4.624991e+06           1.3497
7           T2    376735.5735    4.625012e+06           1.0405
8           T3    376654.2285    4.625092e+06          -0.2475
9           T4    376599.4433    4.625102e+06           2.0679
10          T5    376583.3847    4.625156e+06          -0.0577
11         T10    376827.7944    4.624923e+06           2.5701
12         T11    376913.3321    4.624898e+06           0.8288
13         T12    376870.9558    4.624875e+06           2.6690
14         T13    377084.7724    4.624802e+06           0.3665
15         T14    377082.3201    4.624748e+06           2.4036
16         T15    377212.7656    4.624725e+06           0.4192
17         T16    377205.5081    4.624675e+06           2.5125
18         T17    377283.0665    4.624572e+06           0.4096
19         T18    377193.3729    4.624657e+06           5.0548
20         T19    377144.9286    4.624639e+06           1.5351
21         T20    377040.7237    4.624682e+06           2.0728
22         T21    376889.5710    4.624788e+06           1.2606
23         T22    376757.7699    4.624863e+06           1.8180
24         T23    376967.6411    4.624814e+06           2.4625
25  target 150    378391.9339    4.624010e+06           6.5353
26  target 151    378913.1022    4.623727e+06           2.2165
27  target 152    379006.4858    4.623785e+06           2.5014
28  target 153    379147.0216    4.623625e+06           1.9638
29  target 154    377928.2821    4.624210e+06           6.8589
30  target 161    378109.0032    4.624136e+06           6.0087
31  target 148    378575.1587    4.623888e+06           2.1434
32  target 149    378492.4083    4.624006e+06           2.8081
33  target 155    377543.9294    4.624315e+06           1.8743
34  target 156    377353.1355    4.624463e+06           2.4670
35  target 157    377594.0830    4.624368e+06           2.7190
36  target 158    377830.7642    4.624266e+06           2.9152
37  target 159    377820.6617    4.624186e+06           3.0606
38  target 160    378229.8629    4.624028e+06           1.1820

In [20]:
# replace the column labels
df2.columns=['id','easting','northing','elev']
df2

            id      easting      northing    elev
0           P1  376701.0628  4.624984e+06  5.9625
1           P2  376533.7538  4.625141e+06  5.2526
2           P3  376417.9532  4.625248e+06  1.9856
3           P4  376395.8022  4.625347e+06 -0.0651
4           P5  376553.4078  4.625066e+06  2.7112
5           P6  376670.0570  4.624939e+06  2.6143
6           T1  376763.8347  4.624991e+06  1.3497
7           T2  376735.5735  4.625012e+06  1.0405
8           T3  376654.2285  4.625092e+06 -0.2475
9           T4  376599.4433  4.625102e+06  2.0679
10          T5  376583.3847  4.625156e+06 -0.0577
11         T10  376827.7944  4.624923e+06  2.5701
12         T11  376913.3321  4.624898e+06  0.8288
13         T12  376870.9558  4.624875e+06  2.6690
14         T13  377084.7724  4.624802e+06  0.3665
15         T14  377082.3201  4.624748e+06  2.4036
16         T15  377212.7656  4.624725e+06  0.4192
17         T16  377205.5081  4.624675e+06  2.5125
18         T17  377283.0665  4.624572e+06  0.4096
19         T18  377193.3729  4.624657e+06  5.0548
20         T19  377144.9286  4.624639e+06  1.5351
21         T20  377040.7237  4.624682e+06  2.0728
22         T21  376889.5710  4.624788e+06  1.2606
23         T22  376757.7699  4.624863e+06  1.8180
24         T23  376967.6411  4.624814e+06  2.4625
25  target 150  378391.9339  4.624010e+06  6.5353
26  target 151  378913.1022  4.623727e+06  2.2165
27  target 152  379006.4858  4.623785e+06  2.5014
28  target 153  379147.0216  4.623625e+06  1.9638
29  target 154  377928.2821  4.624210e+06  6.8589
30  target 161  378109.0032  4.624136e+06  6.0087
31  target 148  378575.1587  4.623888e+06  2.1434
32  target 149  378492.4083  4.624006e+06  2.8081
33  target 155  377543.9294  4.624315e+06  1.8743
34  target 156  377353.1355  4.624463e+06  2.4670
35  target 157  377594.0830  4.624368e+06  2.7190
36  target 158  377830.7642  4.624266e+06  2.9152
37  target 159  377820.6617  4.624186e+06  3.0606
38  target 160  378229.8629  4.624028e+06  1.1820

In [22]:
lon2,lat2=transform(utmProj,latlonProj,df2['easting'].values,df2['northing'].values)

print('westbc: ',lon2.min(),'eastbc: ',lon2.max())
print('northbc: ',lat2.max(),'southbc: ',lat2.min())

westbc:  -70.4871323295 eastbc:  -70.4536915755
northbc:  41.7703451582 southbc:  41.7552625631